<?php
session_start();

if (isset($_SESSION['mess_error'])){
    echo '<script>alert("' .$_SESSION['mess_error'] . '");</script>';
    unset($_SESSION['mess_error']);
}

?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="./assets/css/style_login.css">
</head>
<body>
    <div class="login-container">
        <div class="login-box">
            <h2>Login</h2>
            <form action="index.php?action=login" method="POST">
                <input type="hidden" name="formAction" value="signIn">
                <div class="input-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" required>
                </div>
                <div class="input-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <button type="submit" class="btn" name="btnLogin">Login</button>
                <div class="forgot-password">
                    <a href="#">Forgot your password?</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>
